# Generated by Django 5.2.11 on 2026-02-16 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_hard_deadline', models.BooleanField(default=False)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('urgency', models.PositiveSmallIntegerField(default=3)),
                ('importance', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('snoozed', 'Snoozed'), ('blocked', 'Blocked')], default='active', max_length=16)),
                ('follow_up_state', models.CharField(choices=[('created', 'Created'), ('plan_suggested', 'Plan Suggested'), ('checked_in', 'Checked In'), ('closed', 'Closed')], default='created', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('last_nudged_at', models.DateTimeField(blank=True, null=True)),
                ('nudge_count_today', models.PositiveSmallIntegerField(default=0)),
                ('recurrence_rule', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', '-urgency', '-importance', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='assistant', max_length=24)),
                ('action', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
