# Generated by Django 5.2.11 on 2026-02-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crashreport',
            new_name='core_crashr_receive_845749_idx',
            old_name='core_crashr_receive_6720f0_idx',
        ),
        migrations.RenameIndex(
            model_name='crashreport',
            new_name='core_crashr_platfor_983361_idx',
            old_name='core_crashr_platfor_f2f0dc_idx',
        ),
        migrations.RenameIndex(
            model_name='crashreport',
            new_name='core_crashr_source_db026e_idx',
            old_name='core_crashr_source_b1f1d2_idx',
        ),
        migrations.RenameIndex(
            model_name='crashreport',
            new_name='core_crashr_is_fata_5ec153_idx',
            old_name='core_crashr_is_fata_2c4cc1_idx',
        ),
    ]
